### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by uahim** [bitsofpancake/spotify-backup#2]
```
> python spotify-backup.py playlists.txt
  File "spotify-backup.py", line 108
    print u'[{}] {}'.format(time.strftime('%I:%M:%S'), str).encode(sys.stdout.encoding, errors='replace')
                   ^
SyntaxError: invalid syntax
```

any idea?

**Comment by bitsofpancake** [comment]
On Python 3, find and replace all `u'` with just `'` :)

**Comment by uahim** [comment]
did that and I'm getting the exact same error -
I am using Python 3.4.2 on Win32, if that matters

**Comment by bitsofpancake** [comment]
Turns out that a lot needed changing for Python 3. Should work now, thanks.

**Comment by uahim** [comment]
@ bitsofpancake excellent, thank you - it now works like a charm.

**Comment by bitsofpancake** [comment]
Logging out of Spotify on spotify.com (or Facebook if they're connected) should be enough!
